import Head from 'next/head'
import Image from "react-bootstrap/Image"
import styles from '@/styles/Home.module.css'
import Header from 'components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>OrispaX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo_simple.svg" />
      </Head>

      <main className={styles.main}>

        <Header/>

        <div className={styles.center}>
          <Image
            src="/homepage.png"
            alt="Next.js Logo"
            width={448}
            height={448}
          />
        </div>

        <div className={styles.font}>
          Powering DeFi on Celo
        </div>

        <div style={{color:'#ffffff',fontSize:'14px',fontWeight:'400'}}>
          OrispaX is a mobile-first DeFi exchange
        </div>

      </main>
    </>
  )
}
